In [1]:
import tensorflow as tf
from tensorflow import keras
from PIL import Image, ImageFile
import numpy as np 
import pandas as pd
import os
import glob

In [2]:
#model = model.load_model("testmodel.h5")
model = tf.keras.models.load_model('20210625_model_ft_10_2.h5')

In [3]:
target = ['affenpinscher',
'afghan_hound',
'african_hunting_dog',
'airedale',
'american_staffordshire_terrier',
'appenzeller',
'australian_terrier',
'basenji',
'basset',
'beagle',
'bedlington_terrier',
'bernese_mountain_dog',
'black-and-tan_coonhound',
'blenheim_spaniel',
'bloodhound',
'bluetick',
'border_collie',
'border_terrier',
'borzoi',
'boston_bull',
'bouvier_des_flandres',
'boxer',
'brabancon_griffon',
'briard',
'brittany_spaniel',
'bull_mastiff',
'cairn',
'cardigan',
'chesapeake_bay_retriever',
'chihuahua',
'chow',
'clumber',
'cocker_spaniel',
'collie',
'curly-coated_retriever',
'dandie_dinmont',
'dhole',
'dingo',
'doberman',
'english_foxhound',
'english_setter',
'english_springer',
'entlebucher',
'eskimo_dog',
'flat-coated_retriever',
'french_bulldog',
'german_shepherd',
'german_short-haired_pointer',
'giant_schnauzer',
'golden_retriever',
'gordon_setter',
'great_dane',
'great_pyrenees',
'greater_swiss_mountain_dog',
'groenendael',
'ibizan_hound',
'irish_setter',
'irish_terrier',
'irish_water_spaniel',
'irish_wolfhound',
'italian_greyhound',
'japanese_spaniel',
'keeshond',
'kelpie',
'kerry_blue_terrier',
'komondor',
'kuvasz',
'labrador_retriever',
'lakeland_terrier',
'leonberg',
'lhasa',
'malamute',
'malinois',
'maltese_dog',
'mexican_hairless',
'miniature_pinscher',
'miniature_poodle',
'miniature_schnauzer',
'newfoundland',
'norfolk_terrier',
'norwegian_elkhound',
'norwich_terrier',
'old_english_sheepdog',
'otterhound',
'papillon',
'pekinese',
'pembroke',
'pomeranian',
'pug',
'redbone',
'rhodesian_ridgeback',
'rottweiler',
'saint_bernard',
'saluki',
'samoyed',
'schipperke',
'scotch_terrier',
'scottish_deerhound',
'sealyham_terrier',
'shetland_sheepdog',
'shih-tzu',
'siberian_husky',
'silky_terrier',
'soft-coated_wheaten_terrier',
'staffordshire_bullterrier',
'standard_poodle',
'standard_schnauzer',
'sussex_spaniel',
'tibetan_mastiff',
'tibetan_terrier',
'toy_poodle',
'toy_terrier',
'vizsla',
'walker_hound',
'weimaraner',
'welsh_springer_spaniel',
'west_highland_white_terrier',
'whippet',
'wire-haired_fox_terrier',
'yorkshire_terrier'
]

In [4]:
#cut file name to breed
import re
  
def remove(list):
    pattern = '[0-9]'
    list = [re.sub(pattern, '', i) for i in list]
    return list

In [20]:
df = pd.DataFrame(columns = ['Original Filename', 'Original', 'Name 1', 'Pred 1', 'Name 2', 'Pred 2', 'Name 3', 'Pred 3'])
temp = pd.DataFrame(columns = ['Original Filename', 'Original', 'Name 1', 'Pred 1', 'Name 2', 'Pred 2', 'Name 3', 'Pred 3'])

In [24]:
#load file
for name in target:
    mylist = [f for f in glob.glob("./dataset/cropped/test/{0}/*.jpg".format(name))]

    from random import sample
    selected  = sample(mylist,100)
    
    for img in selected:

        row = []
        image_pil = tf.keras.preprocessing.image.load_img(img, target_size=(200, 200, 3))
        image = np.array(image_pil)
        test_image = image / 255
        test_image = test_image.reshape((-1,) + test_image.shape)

        y_pred = model.predict(test_image)

        class_per = y_pred[0]
        icecream = dict(zip(target, class_per))

        row.append(img[41:-4])
        row.append(name)
        mylist = remove(mylist)

        count = 0
        for w in sorted(icecream, key=icecream.get, reverse=True):
            row.append(w)
            row.append(icecream[w])

            count += 1
            if count == 3: break

        new_df = pd.DataFrame([row], columns =  ['Original Filename', 'Original', 'Name 1', 'Pred 1', 'Name 2', 'Pred 2', 'Name 3', 'Pred 3'])
        df = pd.concat([df, new_df], sort=False)

In [25]:
df["Original"] = df['Original'].str.replace(r'\d+','')
df

C:\Users\BVer\miniconda3\envs\dog\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.

,Original Filename,Original,Name 1,Pred 1,Name 2,Pred 2,Name 3,Pred 3
0,10627_3032,affenpinscher,affenpinscher,0.998480,brabancon_griffon,0.001119,cairn,0.000077
0,10627_4597,affenpinscher,affenpinscher,0.997363,bouvier_des_flandres,0.001573,shih-tzu,0.000261
0,10627_13553,affenpinscher,affenpinscher,0.999512,brabancon_griffon,0.000241,shih-tzu,0.000096
0,10627_8099,affenpinscher,affenpinscher,0.481901,tibetan_terrier,0.161918,scottish_deerhound,0.156103
0,10627_2894,affenpinscher,affenpinscher,0.999774,brabancon_griffon,0.000112,bouvier_des_flandres,0.000029
...,...,...,...,...,...,...,...,...
0,n02094433_6258,yorkshire_terrier,yorkshire_terrier,0.675021,silky_terrier,0.255938,australian_terrier,0.025477
0,n02094433_2114,yorkshire_terrier,yorkshire_terrier,0.574092,silky_terrier,0.399236,australian_terrier,0.013612
0,n02094433_1824,yorkshire_terrier,yorkshire_terrier,0.950386,silky_terrier,0.042071,australian_terrier,0.005286
0,n02094433_2229,yorkshire_terrier,silky_terrier,0.711840,yorkshire_terrier,0.244899,australian_terrier,0.037191
0,n02094433_1634,yorkshire_terrier,yorkshire_terrier,0.940865,silky_terrier,0.057571,australian_terrier,0.000835

In [53]:
len(df[df['Original'] == df['Name 1']]) / len(df) * 100

80.30833333333334

In [52]:
(len(df[df['Original'] == df['Name 1']]) + len(df[df['Original'] == df['Name 2']]) + len(df[df['Original'] == df['Name 3']])) / len(df) * 100

95.19166666666666

In [71]:
for name in target:
    
    temp = pd.DataFrame(columns = ['Original Filename', 'Original', 'Name 1', 'Pred 1', 'Name 2', 'Pred 2', 'Name 3', 'Pred 3'])
    temp = pd.concat([temp, df[df['Original'] == name]], sort=False)
    pred_1 = len(temp[temp['Original'] == temp['Name 1']]) / len(temp) * 100
    pred_3 = (len(temp[temp['Original'] == temp['Name 1']]) + len(temp[temp['Original'] == temp['Name 2']]) + len(temp[temp['Original'] == temp['Name 3']])) / len(temp) * 100
    if(pred_3 < 90):
        print(name)
        print(pred_1)
        print(pred_3)

beagle
61.0
88.0
cocker_spaniel
75.0
88.0
english_setter
77.0
86.0
giant_schnauzer
61.0
85.0
lakeland_terrier
71.0
88.0
rhodesian_ridgeback
35.0
76.0
standard_schnauzer
60.0
88.0
tibetan_terrier
60.0
88.0